apiVersion: v1
kind: Service
metadata:
  name: feature-engine
  namespace: regime
  labels:
    app: feature-engine
spec:
  type: ClusterIP
  selector:
    app: feature-engine
  ports:
    - port: 6002
      targetPort: 6002
      protocol: TCP
