apiVersion: v1
kind: Service
metadata:
  name: backtesting
  namespace: regime
  labels:
    app: backtesting
spec:
  type: ClusterIP
  selector:
    app: backtesting
  ports:
    - port: 6004
      targetPort: 6004
      protocol: TCP
